ci:
  autoupdate_schedule: monthly
repos:
- hooks:
  - args:
    - --py36-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v2.29.0
- hooks:
  - id: check-yaml
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 21.9b0
- hooks:
  - id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.9.3
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2
