name: Linter

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: skaneria-nydig/python-code-linter@main
      - uses: actions/setup-python@v2

      - name: Test With Pytest
        run: |
          pip install -U pytest
          pytest test/
