name: test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "python3.x"
      - uses: mmdbalkhi/python-code-linter@V1
        with:
          src: "."
      - name: Test With Pytest
        run: |
          pip install -U pytest
          pytest test/
